name: Prepare tauri project
description: Prepare a tauri project for upcomming commands

inputs:
  platform:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Setup desktop app pnpm
      id: prepare-tauri
      uses: ./.github/actions/prepare_pnpm
      with:
        working-directory: desktop

    - name: install Rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
        targets: ${{ inputs.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

    - name: install dependencies (ubuntu only)
      if: inputs.platform == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
