name: Bundle

on:
  push:
    tags:
      - "v*.*.*"

# on:
#   pull_request:

jobs:
  bundle_desktop:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Setup Tauri
        id: prepare-tauri
        uses: ./.github/actions/prepare_tauri
        with:
          platform: ${{ matrix.platform }}

      - name: Get Tags
        id: tag
        uses: ildug/get-tag-action@v1
      - name: Display version
        run: |
          echo "Version ${{ steps.tag.outputs.version }}"
          echo "Tag ${{ steps.tag.outputs.tag }}"

      - name: Update Package Version
        uses: jossef/action-set-json-field@v2.2
        with:
          file: desktop/tauri.conf.json
          field: package.version
          value: ${{ steps.tag.outputs.version }}

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        with:
          # tagName: ${{ steps.tag.outputs.tag }}
          # releaseName: ${{ steps.tag.outputs.tag }}
          releaseDraft: true
          args: ${{ matrix.args }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            desktop/target/**/release/bundle/**/*.dmg
            desktop/target/**/release/bundle/**/*.app
            desktop/target/release/bundle/**/*.dmg
            desktop/target/release/bundle/**/*.app

            desktop/target/release/bundle/**/*.deb
            desktop/target/release/bundle/**/*.rpm
            desktop/target/release/bundle/**/*.AppImage

            desktop/target/release/bundle/**/*.exe
            desktop/target/release/bundle/**/*.msi

      # # Project rules must be updated to push changes
      # # GH013: Repository rule violations found for refs/heads/main.
      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Bump version to ${{ env.VERSION }}
      #     branch: main
