name: Bundle

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  bundle_core:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: core
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        # os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - run: make bundle
      - uses: actions/upload-artifact@v4
        with:
          name: core-${{ matrix.os }}
          retention-days: 1
          path: core/dist/*

  bundle_desktop:
    needs: bundle_core
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        # os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          echo "Tag name: ${{ github.ref_name }}"
          TAG_NAME=${{ github.ref_name }}
          if [[ $TAG_NAME =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION=${BASH_REMATCH[1]}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "The tag $TAG_NAME is not in the expected format 'v<MAJOR>.<MINOR>.<PATCH>'"
            exit 1
          fi
          
      - uses: actions/checkout@v4
      - name: Download bundle artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-${{ matrix.os }}
          path: core/dist

      - name: Linux Only - Install Extra Libs
        if: runner.os == 'Linux'
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y build-essential libgtk-3-dev libssl-dev libsoup2.4-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

      - name: Setup Webapp
        id: prepare-webapp
        uses: ./.github/actions/prepare_webapp
        with:
          working-directory: webapp

      - name: Set Version
        working-directory: webapp
        run: pnpm run set-version ${{ env.VERSION }}

      - name: Bundle
        working-directory: webapp
        run: pnpm run build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            webapp/src-tauri/target/release/bundle/**/*.dmg

            webapp/src-tauri/target/release/bundle/**/*.deb
            webapp/src-tauri/target/release/bundle/**/*.rpm
            webapp/src-tauri/target/release/bundle/**/*.AppImage

            webapp/src-tauri/target/release/bundle/**/*.exe

      # # Project rules must be updated to push changes
      # # GH013: Repository rule violations found for refs/heads/main.
      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Bump version to ${{ env.VERSION }}
      #     branch: main
