name: Bundle

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  bundle_core:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: core
    strategy:
      fail-fast: false
      matrix:
        # os: ["macos-latest"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - run: make bundle
      - uses: actions/upload-artifact@v4
        with:
          name: core-${{ matrix.os }}
          path: core/dist/*

  bundle_desktop:
    needs: bundle_core
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: ["macos-latest"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - name: Linux Only - Install Extra Libs
        if: runner.os == 'Linux'
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libsoup2.4-dev
      - uses: actions/checkout@v4
      - name: Download bundle artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-${{ matrix.os }}
          path: webapp/src-tauri/bin

      # PNPM
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "webapp/pnpm-lock.yaml"

      - name: Get pnpm store directory
        shell: bash
        working-directory: webapp
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: webapp
        run: pnpm install
      # PNPM -- END

      - name: Bundle
        working-directory: webapp
        run: pnpm build

      - uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: webapp/src-tauri/target/release/bundle/*
