name: Quality

on:
  pull_request:

jobs:
  webapp_quality:
    name: Webapp Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v4
      - name: Setup Webapp
        id: prepare-webapp
        uses: ./.github/actions/prepare_pnpm
        with:
          working-directory: webapp

      - name: Lint
        run: |
          pnpm run lint

      - name: Tests
        run: |
          pnpm run test

      - name: Build
        run: |
          pnpm run build

  desktop_quality:
    name: Desktop Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: desktop
    steps:
      - uses: actions/checkout@v4
      - name: Setup Tauri
        id: prepare-tauri
        uses: ./.github/actions/prepare_tauri
        with:
          platform: ${{ runner.os }}

      - name: Build
        run: |
          pnpm run build

  core_quality:
    name: Core Quality
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint
        run: |
          make lint

      - name: Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: |
          make test

      - name: Build
        run: |
          make bundle
