name: Quality

on:
  pull_request:

jobs:
  core:
    name: Core (Rust)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features

  webapp:
    name: Webapp (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v4
      - name: Setup Webapp
        id: prepare-webapp
        uses: ./.github/actions/prepare_pnpm
        with:
          working-directory: webapp

      - name: Lint
        run: |
          pnpm run lint

      - name: Tests
        run: |
          pnpm run test

      - name: Build
        run: |
          pnpm run build

  desktop:
    name: Desktop (Tauri)
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-22.04"
          #   args: ""
          # - platform: "windows-latest"
          #   args: ""
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: desktop
    steps:
      - uses: actions/checkout@v4
      - name: Setup Tauri
        id: prepare-tauri
        uses: ./.github/actions/prepare_tauri
        with:
          platform: ${{ matrix.platform }}

      - name: Build
        run: |
          pnpm run build
